spring:
  application:
    name: gateway
server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie

jwt:
  config:
    login-url: /auth/login

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000